### PR TITLE
Enable redirecting to parent in entity/view for some types - closes #363

### LINKED ISSUE #363: Enable redirecting to parent in entity/view for some types
`entity/view` does not make sense for some entity types. For example, `input-challenge-*, `single-choice-*`, and even `solution` don't make sense without their context. IMHO, instead of having a page for those entities, we should instead redirect to their parent. This would make the workflow easier for editors, since one comes directly back to the corresponding exercise after editing. Furthermore, Google wouldn't index those useless pages.

Proposed solution: Add to `types.config.php` some parameter like `redirect-to-parent => true` (or `has-view => false`, ...). Then `indexAction()` in `Entity/Controller/PageController` reads the config of the entity and if this parameter is set, fetches its parents and redirects to the first.

@arekkas: What do you think? And is my proposed solution even possible?

### PR DESCRIPTION
**Pull request by Knorrke**
I added the possibility to redirect to the parent. Please take a look if it's OK to use the already existing "toType" parameter, even though "parent" is actually not a type.

The redirecting happens for:
- grouped-text-exercise
- SC/MC answers
- input exercises
- solution
- hint

Also, is a multiple redirect a problem? Because for example a solution of grouped-text-exercise redirects to the grouped-text-exercise which redirects to the exercise-group.

### CODE REVIEW

**Comment by arekkas** [comment]
Did you introduce the parent type to avoid setting the types manually?

**Comment by arekkas** [comment]
Because in most cases you can replace `parent` with `text-exercise-group` and avoid the extra logic and implications of/for `parent`

**Comment by Knorrke** [comment]
No the problem is that the parent isn't always text-exercise-group but also text-exercise. Another option I thought of would be changing toType to an array instead of a single string and then using the first type that matches the condition. Maybe that's cleaner? Or do you have a different idea?

**Comment by arekkas** [comment]
Ah I see, that makes sense. What would happen if the child had two parents? For example a course page which has been added to more than one course.

**Comment by Knorrke** [comment]
Currently this isn't allowed because they have multiple => false for their parents, however they could be added to two different types (so for example a text-solution added to both an text-exercise and a grouped-text-exercise)
And then allways the first one would be chosen for redirect. I essentially use the same logic as those backlinks currently do (e.g. https://github.com/serlo-org/athene2/blob/master/src/module/Ui/templates/entity/page/text-solution.twig#L5 )

**Comment by arekkas** [comment]
Sounds good!

**Pull request merged**
