### PR TITLE
Add new exercise type math-puzzle

### PR DESCRIPTION
**Pull request by inyono**
Things to consider before merging/deploying:

* [ ] Needs new type `math-puzzle` in database
* [ ] Needs translation of new strings (my PoEdit still doesn't work)
* [x] Coding style is still messy (@arekkas: Should @liquidizer fix this before deployment? I jshint-ignored the files for now)

math puzzle

### CODE REVIEW

**Comment by inyono** [comment]
And maybe we should clean up `src/test/math-puzzle/` beforehand so that it e.g. uses `src/assets/bower_components`. Currently, it is shipped with its own version of RequireJS and jQuery.

**Comment by inyono** [comment]
* [ ] And the author set by GitHub is weird. Did I take the wrong email address @liquidizer? Just copied the author from your other commits.

**Comment by arekkas** [comment]
>  And maybe we should clean up src/test/math-puzzle/ beforehand so that it e.g. uses src/assets/bower_components. Currently, it is shipped with its own version of RequireJS and jQuery. 

yes please

> And the author set by GitHub is weird. Did I take the wrong email address @liquidizer? Just copied the author from your other commits.

not sure, probably wrong email!

> Needs new type math-puzzle

please include this in *this* PR

> Needs translation of new strings (my PoEdit still doesn't work)

I haven't heard back from the PoEdit issue. I'll check if they released a new version with the bugfix...

> Coding style is still messy (@arekkas: Should @liquidizer fix this before deployment? I jshint-ignored the files for now)

I know this can be frustrating and annoying, but please clean up the code. It makes it so much easier to maintain.

**Comment by arekkas** [comment]
Everything else looks wonderful!

**Comment by inyono** [comment]
>>  Needs new type math-puzzle

> please include this in this PR

Should have been more clear: We have to add the type to the database before deploying, but it's existing already :)

**Comment by arekkas** [comment]
Get it :) Could you add it to sql/dump.sql so new dev environments have that type? I will migrate this live when it hits

**Comment by arekkas** [comment]
Hey, is this good for review?

**Comment by inyono** [comment]
for review, yes. not for merge, though, I'm currently modifying the dump

**Comment by inyono** [comment]
Done except for the translations

**Pull request merged**
