### PR TITLE
closes #505 - allow fullscreen for videos

### LINKED ISSUE #505: allow fullscreen for videos
see iframe propertie allowfullscreen: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

### PR DESCRIPTION
**Pull request by Knorrke**
closes #505 by adding allowfullscreen attribute to iframe (reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)

Wait with merging until #503 and #504 are merged

### CODE REVIEW

**Comment by arekkas** [comment]
Please rebase the PR, it includes commits which are on master already

**Comment by Knorrke** [comment]
@arekkas aren't those the commits from docker PRs? I can rebase to master too, but can't test it that way, so I thought I wait until the docker PRs are merged.

**Comment by arekkas** [comment]
Ah sure, that makes sense

**Comment by arekkas** [comment]
now it needs rebasing ^^

**Comment by arekkas** [comment]
ah right, because the troubleshooting

**Comment by Knorrke** [comment]
done @arekkas

**Pull request merged**
