### PR TITLE
New German Starting Page

### LINKED ISSUE #420: include header and new subjects on starting page
changes to serlo.org/:
- add header
- add three more subjects
- delete press section
- Update from Sprint Planning: replace numbers (blue section) with project description and link to serlo.org/serlo. So only partners remain below subject selection

Mock up: https://docs.google.com/drawings/d/1rmTtmv0rKjhGNFaXEZD6itr6VnOvtT3wK9bcNKn_bKQ/edit

dependencies until pr:
- visuals for the subjects from vasiliki
- final go from Botho (design)
- final go from Simon (content)

### PR DESCRIPTION
**Pull request by JonasBley**
closes #420 
The Symbols are now bigger, the arrows are grey and inline and the css file is tidied up.
Screenshots:
screenshot 2016-11-26 14 12 32
screenshot 2016-11-26 14 12 10
screenshot 2016-11-26 14 12 06

### CODE REVIEW

**Comment by arekkas** [comment]
@JonasBley I suggest to discuss your awesome work here after our sprint planning on thursday!

**Comment by arekkas** [comment]
It looks like you downgraded the athene2-editor git submodule. The right commit hash would be 509738185a07ddfce286c6bc024dd874f394da68

**Comment by JonasBley** [comment]
I'm not quite sure what that submodule is about. Sure, let's discuss everything on thursday, there is probably a lot of room for improvement.

**Comment by elbotho** [comment]
So you'd add this on thursday? 👍

**Comment by inyono** [comment]
Regarding submodule, see See [Update the locked version](https://github.com/serlo-org/athene2/wiki/Editor-development-workflow#update-the-locked-version)

**Comment by JonasBley** [comment]
The colours aren't standard Serlo colours, so I dont think we have a variable for them. The submodule should be updated now right? Im not sure...

**Comment by arekkas** [comment]
yup, thanks!

**Pull request merged**
