### PR TITLE
Revert "Hopefully fixed an issue with the requirejs build"

### PR DESCRIPTION
**Pull request by arekkas**
Reverts serlo-org/athene2#29

@jkempff seems like the issue still exists: https://gitter.im/serlo-org/de-serlo-org?at=5530f4d38c86646906dd4c42

### CODE REVIEW

**Comment by jkempff** [comment]
..damn! Like I said, it occures very randomly, at least on my machine..

**Comment by jkempff** [comment]
if it helps, I had no problems with

`node v0.12.1` and `npm v2.5.1`

**Comment by arekkas** [comment]
Ok I'll update the dependencies

**Comment by arekkas** [comment]
@jkempff the issue has been solved for @daFischer ... I'll check with benni today why it doesn't work on his system :)

**Pull request closed without merging**
