### PR TITLE
fix: add alias path for entity children using parent

### LINKED ISSUE #657: URL of course: Missing path & common course ID
On course pages the path of content in url is not generated (Example: /mathe/funktionen/). You can only see the ID of each course page. 

Also a course has no common ID, you can only use the ID of each course page. 

Missing course path & no common ID is for example a problem in Google Analytics. We are not able to detect correct number of page views, for example in maths. We need the path to search for keyword "mathe". Also it's not possible to detect number of course views, only of each course page. 

Example course page:

https://de.serlo.org/51522/nullstellen

### PR DESCRIPTION
**Pull request by Knorrke**
add alias for course pages and exercises using parent taxonomy (fixes #657)

### CODE REVIEW

**Comment by Knorrke** [comment]
@arekkas do the aliases get refreshed automatically over time? I've found that the refresh command only refreshes ~10% by default and passing `--percentile=100` resultet in an error:
```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/src/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2649
```

**Comment by arekkas** [comment]
I don't think there's currently a cron job for that. The percentile option is there for exactly that (not overflowing the memory buffer)

**Comment by SimonKoehl** [comment]
is this already fixed?
Did you think about the SEO while solving this? We need redirects for all current course page URLs, so we don't lose the search engine ranking on this content.

**Comment by Knorrke** [comment]
this is implemented, however the alias only refresh with new revisions, not automatically. So over time they should be correct, but atm there are a lot which still have the old alias. E.g:
- previous: https://de.serlo.org/65158/caesars-geheime-botschaft
- new: https://de.serlo.org/informatik/informatik-mensch-gesellschaft/verschluesselung/caesar-verschluesselung-einer-tabellenkalkulation-programmieren/caesars-geheime-botschaft

This was a SEO issue, yes, but not sure what you mean by your question, if I thought about it? The reasons for the change are explained in #657, but in short:
- There was no way to check the views for a course, only for individual course pages
- Course views didn't count into statistics like "views in `/mathe`

Redirects are handled as in every other entity, so that shouldn't be a problem.

**Comment by SimonKoehl** [comment]
Ok great! With SEO I just ment possible negative effects like if there weren‘t redirects.

**Pull request merged**
