### PR TITLE
WIP Multiple Choice / Single Choice exercises

### PR DESCRIPTION
**Pull request by inyono**
First draft for the entity type for multiple choice / single choice exercises.

## New type `choice-exercise`

Represents a multiple choice / single choice exercise. It consists of three fields:
* `type` determines whether the exercise is MC or SC
* `content` for the assignment itself
* `changes` like other entities.

Moreover, it may have to types of children:
* one or more `choice-exercise-choice` that each represent a single choice
* one `text-hint` that represents a hint like in other types of exercises

## New type `choice-exercise-choise`

Represents a choice of a multiple choice / single choice exercise. It consists of three fields:
* `correct` states whether this choice is a correct solution or a wrong choice
* `content` for the content of the choice itself
* `changes` like other entities.

Moreover, it may have a `text-hint` child like in other types of exercises. We could use this for feedback and stuff. Maybe add a new type for this to make the difference to other hints clear.

Missing stuff:
* [ ] No forms yet (we have to decide whether we wait for the editor abstraction)
* [ ] No templates yet (design pending)
* [ ] Probably not everything right yet. E.g., the `choice-exercise-choice` should have a link to its parent (like `course-page`s do)

Feedback welcome!

### CODE REVIEW

**Comment by inyono** [comment]
Another possible approach: Add something like `type` and `choice-exercise-choice` to the already existing type `text-exercise`/`text-exercise-group`. With this, you could "transform" already existing exercises to choice exercises. Needs more cases in the template, though.

**Comment by arekkas** [comment]
I don't think there should be a new type dedicated to exercise content. As you mentioned, we should reuse `text-exercise` and add `text-exercise-choice`. This would allow to reuse all the exercises we have. So no new hints needed neither "musterlösungen" :)

**Comment by inyono** [comment]
Agreed.

**Comment by arekkas** [comment]
So what I would do is write a simple template (and a jquery extension (e.g. bound to class `text-exercise-choice`) which checks on click of a submit button if the checked boxes match the `data-correct-choice` is set / true.

But by saying that I realize that, because we need to generate the submit button only once, this needs a little bit more thought. My current idea would be, for example, to check in the text-exercise template if children of type text-exercise-choice exist and if yes, render a "submit" / "check solution" button

**Comment by SimonKoehl** [comment]
Hi @inyono , there is a little change, Botho, Aeneas and I discussed today:
- only the negative feedback schould be part of the the answer-type
- there should be an additional input for positive/success feedback, that could optionally be added to the exercise, independent from the single answers.

**Comment by inyono** [comment]
superseded by #310 and #293.

**Pull request closed without merging**
