### PR TITLE
New design for discussions

### LINKED ISSUE #395: New design for discussions
- [x] Don't collapse textarea for comments.
- [x] Replace info-text with shorter placeholder in textarea.
- [x] Remove title for discussions
- [x] Redesign textarea
- [x] Rename "Discussions" to "Comments"

### PR DESCRIPTION
**Pull request by Knorrke**
Implemented the new design for discussions. Closes #395 

Please update the translation file when merging this, so that the placeholders of the textareas and button texts are translated.

The translations should be as follows:
Ask a question or suggest an improvement -> Frage oder Verbesserungsvorschlag
Comment -> Kommentar abschicken
Your answer -> Deine Antwort
Reply -> Antwort abschicken

Thank you

### CODE REVIEW

**Comment by arekkas** [comment]
@arekkas check translation with forms

**Comment by arekkas** [comment]
Sorry that this is still open, there are issues again with POEdit...

**Comment by Knorrke** [comment]
No problem. I updated the language file but i think there might be something wrong with it because of the many changes. @inyono wanted to help me with this on tuesday.

**Comment by arekkas** [comment]
Yup there's a lot of removed LOCs in the translations, not sure if that's ok. @inyono if poedit fails, could be this helper missing: https://github.com/serlo-org/athene2/pull/396/files#diff-395d6e5ea9e3fc42a9bf983cf8548b95R3

**Comment by Knorrke** [comment]
ok, so updating the language file did work now :) I haven't uploaded it to crowdin yet, ping @inyono

**Comment by Knorrke** [comment]
ping @arekkas, what's the status of this?

**Comment by arekkas** [comment]
do you want to include the translation files in the PR or should they be a different PR? sorry for the delay here, again... :)

**Comment by inyono** [comment]
My bad, I wanted to add the translations. Will do today

**Comment by Knorrke** [comment]
They're already included. I did this together with @inyono a week ago, so it should be ok. They're just not yet uploaded to crowdin, but @inyono wanted to do this after merge

**Comment by inyono** [comment]
done

**Comment by Knorrke** [comment]
ping @arekkas

**Pull request merged**
