### PR TITLE
WIP Add `text-input-solution` to `text-exercise`

### PR DESCRIPTION
**Pull request by inyono**
First draft for exercises that check the answer given by the user.

## New type `text-input-solution`

Represents a correct answer. It consists of two fields:
* `content` states the correct solution, e.g. `5`
* `validator` determines how the input of the user is validated. Some examples:
  * validator `exactlyTheSame`: Only accepts input that is exactly the same as the solution, e.g. `5` in this case.
  * validator `numberEquality`: Accepts input that has the same value, e.g. `5.0`, `10/2`.
  * validator `deviation`: Accepts input that is in some range of the solution, e.g. for deviation of 0.5: accepts everything between `4.5` and `5.5`.
  * ...
  * for the MVP, `exactlyTheSame` is probably enough.

## Add child `text-input-solution` to `text-exercise`

`text-exercises` may have one or more `text-input-solution`s. Each represents one (or possible more through validators) correct answers. We then check in the front end if the user input is correctly validates by one of the `text-input-solutions`. So for the MVP, you may add one or more `exactlyTheSame` answers.

Open things:
* [ ] Is this a logical way to represent solutions? I think that we need some kind of "validator"s (or whatever they will be named) for range of solutions. It would probably be nice if we could add validators dynamically with some kind of script language. Moreover, some validators may need arguments (like the `deviation` above). Altogether: I'm not sure whether this is a good way to do this. 
* [ ] Naming probably needs some improvements, too ;)

Missing stuff:
* [ ] No forms yet
* [ ] No templates yet
* [ ] Probably syntax is not correct, yet

Feedback welcome!

### CODE REVIEW

**Comment by inyono** [comment]
We could add a new type for this, too, ofc. But I think we don't need that and this approach makes transforming existing exercises easier I think

**Comment by arekkas** [comment]
I think the challenge will be to write a form editor that works with the validator requirements plus usability might suffer if this get's too complicated.

**Comment by inyono** [comment]
Yeah. But I think we should keep the use case in mind for the future. Because only "exact" solutions aren't enough for all exercise types, I think.

**Comment by arekkas** [comment]
After some thinking I do not believe that separating the validator and content field is the right way. The reason is that you assume there will only one correct solution which e.g. is a number. But in fact, we might want to write validators which validate against multiple correct solutions (or representations of them). Additionally, the content field is just a string right now. We would have to write special syntax for range validators (e.g. `X-Y`) or other types of validators.

I would therefore prefer to move the logic up and have e.g.:

- `input-exercise-numerical-exact`
- `input-exercise-numerical-equal`
- `input-exercise-numerical-range`
- `input-exercise-familiarity` (e.g. bus, auto, bahn, fahrrad)

What do you think?

/cc @SimonKoehl

**Comment by arekkas** [comment]
That way, we would be able to have different formats for hints or feedback as well. We only need to componetize the JS stuff so we don't have to write lots of boilerplate

**Comment by inyono** [comment]
If I understand you correctly, then you want to create multiple types that each have one solution (resp. more through the validators). But what if I want, e.g., two exact solutions?

**Comment by arekkas** [comment]
Two exact solutions would be a problem with the current approach as well, right?

**Comment by inyono** [comment]
No, because you can add multiple valdiators to one exercise. So I could even combine different validators. E.g. "Find one root of the function" -> Solutions 0 (exact), Interval from 2 to 3 (range), 5 (exact). But I find this more useful when you don't work with numbers.

**Comment by arekkas** [comment]
What if all of them are required to pass?

**Comment by inyono** [comment]
Like? Not sure what you mean? Do you mean multiple inputs (So we check interim results)?

**Comment by arekkas** [comment]
A combination of validation steps. E.g.

The answer needs to be in the wordfamily of "Color" and of "Feeling". You are currently expecting, that multiple answers always OR - what happens if they need to be AND or a combination of OR, AND?

I'll need a little bit more time to come up with a better plan. Let me think :)

**Comment by inyono** [comment]
Okay, I think I get what you mean. Maybe we also need some kind of transducer (like OR, AND, or whatever you like xD). Moreover, this model doesn't cover multiple input fields, yet.

**Comment by arekkas** [comment]
I would say focus on MC first, it will gives us time to get a better understanding of the problem!

**Comment by inyono** [comment]
superseded by #294

**Pull request closed without merging**
