### PR TITLE
closes #427 - add CSRF tokens

### LINKED ISSUE #427: Add CSRF tokens
We must add CSRF tokens to all forms:

https://framework.zend.com/manual/2.4/en/modules/zend.form.element.csrf.html

### PR DESCRIPTION
**Pull request by Knorrke**
closes #427

### CODE REVIEW

**Comment by arekkas** [comment]
Nice @Knorrke - did you test all forms manually?

**Comment by Knorrke** [comment]
I only tested some of them (the Authorization and Entity forms), but could do this tomorrow if needed. But I had to do it manually, yes, is there a way to write an automated test for this?

**Comment by arekkas** [comment]
> But I had to do it manually, yes, is there a way to write an automated test for this?

I would love to have automated tests, unfortunately we need to come up with the whole toolchain for that because it requires integration tests, not unit tests. We can go through it together tomorrow!

**Comment by Knorrke** [comment]
@arekkas this should be finished now, please take a look. Espacially: I used a lot of view helpers to load the forms, is this ok, or should I change this somehow?
I also manually tested all pages, so there shouldn't be any problems in the functionality.

**Comment by Knorrke** [comment]
@arekkas As discussed I now removed the view helpers and passed the forms in the controller directly to the view. Looks a lot better now, thanks for the tip!
I sticked with the view helper for uuid trash and purge actions, because these forms are used in many controllers and I think it's much easier to use this way, than passing the form in every controller.

So again, ready for review ;-)

**Pull request merged**
