### PR TITLE
Landing page hotfix

### LINKED ISSUE #499: Subjects on mobile not clickable

### PR DESCRIPTION
**Pull request by JonasBley**
Padding is a little different, but it looks good. Closes #499

### CODE REVIEW

**Comment by arekkas** [comment]
Good for 👀 ?

**Comment by Knorrke** [comment]
I don't know why, but the diff shown in "Files changed" is wrong, as most of this is already merged into master. The only change is removing the div at [line 198](https://github.com/serlo-org/athene2/pull/500/files#diff-06a235f32ae65fd380705581e961060fL198) as discussed in #499

**Comment by JonasBley** [comment]
Yep, the first two commits are already deployed

**Comment by arekkas** [comment]
Please rebase on master so this PR is easier to review

**Comment by arekkas** [comment]
nvm I thought it's more code ;D

**Pull request merged**
