### PR TITLE
German Starting Page re-design

### PR DESCRIPTION
**Pull request by JonasBley**
Added header: Serlo Die freie Lernplattform
Removed Presse

### CODE REVIEW

**Comment by JonasBley** [comment]
germanstartingpage

**Comment by JonasBley** [comment]
In Absprache mit Simon

**Comment by JonasBley** [comment]
Maybe I'd rather do a 1 - 2 - 2 - 1 arrangement than a 3 - 3? I dont know

**Comment by JonasBley** [comment]
It was 2 - 2 - 2 before, with the Press part

**Comment by arekkas** [comment]
Hm, it was originally discussed that we are going to do some A/B testing with this. Additionally, I was not involved in the decision making on this. What happend @SimonKoehl ?

**Comment by arekkas** [comment]
Oh, and of course thanks for the PR :)

**Comment by arekkas** [comment]
@SimonKoehl we should discuss this next wednsday when our original meeting was scheduled on the landing page. I don't like the changes suggested, there's a lot of visual clutter, logos, duplication and emptyness.

@JonasBley please stay tuned while we figure this stuff out :)

**Comment by JonasBley** [comment]
Here is the link Simon's mock up of the German starting page redesign:
https://docs.google.com/drawings/d/1rmTtmv0rKjhGNFaXEZD6itr6VnOvtT3wK9bcNKn_bKQ/edit?ts=57e3e842
I'll stay tuned ;)

**Comment by SimonKoehl** [comment]
@arekkas nothing changed from what we discussed. I just asked Jonas to start implementing iteration one, which our designers and you agreed on

**Comment by SimonKoehl** [comment]
@JonasBley Thanks for the first steps!

**Comment by JonasBley** [comment]
Btw: Here is the version with 1-2-2-1: Looks better imo, what do you think?
germanstartingpage2

**Comment by inyono** [comment]
I have to agree with @arekkas. Although I mostly like the mock up in https://github.com/serlo-org/athene2/pull/419#issuecomment-249380054, I don't like this intermediate version because of its asymmetry.

**Comment by arekkas** [comment]
@SimonKoehl I know that we wanted to do it iteratively, but since the landing page is like our store front, we should put more effort into redesigning it, e.g. have a design (PDF/PNG) mock up. This was also part of what we discussed

**Comment by arekkas** [comment]
@JonasBley thanks for the update it looks better and I think there are areas for improvement:

1. We have now 2x serlo and 2x serlo logo, which looks weird because of repetition
2. The partner area and the Serlo area clash, because they do not obey the gestalt law of order but are grouped together by the gestalt law of proxmity (visual clutter)
3. There is now 5 logos on the landing page
4. There are no (invisible) constraints, everything floats in it's own space and size

My suggestion to this is that we postpone this PR, discuss this as a group in person, get someone to make us some nice designs in photoshop and implement those.

To explain my self on this: We worked a lot on serlo with half-baked "let's fix this with css in browser hacking until it feels ok" approaches and it almost always ended up looking awful. There are still a lot of areas where I just hacked stuff that are really uncomfortable looking at. Once we as developers (or in general people who have never touched photoshop/indesign) had something real to look at, the things suddenly got a real nice look. It also got us to discuss areas we thought need improvement and iterate faster over this stuff. Fixing design issues with html and css works in the beginning, but get's exhausting really quickly and in turn results in unsatisfying experiences. We should not make a step backwards now and fall back in to those same workflows for the most important pages that serlo has.

So, in preparation to the new landing page, I want to take an even more structured approach. The landing page is something that partners, press and many many users see first. It must show us from our best side. To achieve that, we should not only get someone experienced in web and ui design to help us, we should also take a data driven approach at this by usind A/B testing in order to get the best results.

All of these things are why I think that we need to set up a in-persona meeting, talk through the steps and ultimatively decide how we want to progress. Our next sprint planning would be the perfect fit for that and in preparation @SimonKoehl and me and anyone ( @Knorrke @inyono @JonasBley ...) interested will decide what needs to be done until then.

**Comment by SimonKoehl** [comment]
Hey @arekkas @JonasBley @inyono sorry, I made three mistakes:
- not writing a detailled issue, so everybody knows what this is about
- not including this in the planning/dev-process
- not clarifying with you the "owner" of this task as the person who should be addressed with criticism etc. to avoid information crossfire for the developer

backround: Ashoka and Phineo are deciding on funding applications in october and I wanted them to see an obvious sign of progress towards our vision of a open learning platform - beyond mathematics

For my understanding:  Does "pull request" mean, this is finished? Because of course it's not  

Wednesday: I don't know about a meeting yet. What's the plan?

Best!

**Comment by arekkas** [comment]
@SimonKoehl sorry, I misread the meeting. We have something scheduled for the feedback tool, not the landing page on wed. If you are in munich tomorrow we can further discuss the landing page there or before/after the feedback thing.

**Comment by Knorrke** [comment]
@SimonKoehl could you clarify what should be included in the pull request, before merging it? As I see it that's the only misunderstanding here. If this version isn't ment to be a temporary starting page then I think the discussion about its design is unnecessary.

**Comment by arekkas** [comment]
@SimonKoehl merged pull requests go to production with the next deployment

**Comment by arekkas** [comment]
so @Knorrke is right here, it was a misunderstanding. If it's not meant to go into production please add a *work in progress* or discuss or something like that in the title/description! :)

**Comment by SimonKoehl** [comment]
Ok @Knorrke, I move this to an issue, where it belongs

**Comment by SimonKoehl** [comment]
https://github.com/serlo-org/athene2/issues/420

**Pull request closed without merging**
