### PR TITLE
Small change for the home_learn-svg on en.serlo.org

### PR DESCRIPTION
**Pull request by JonasBley**
Sorry, I needed to change the home_learn.svg again, didn't look too good.

### CODE REVIEW

**Comment by inyono** [comment]
There are some git conflicts. Did you pull from master before creating the pull request?

**Comment by JonasBley** [comment]
No I didn't, thought these conflicts don't matter. I will pull from master and create a new pull request later then

**Comment by inyono** [comment]
Can't merge when there are conflicts. You don't need to create a new pull request. Just pull the changes from master (and resolve the conflicts). After that, push again to the branch (probably while using `--force` since you changed your commit history)

**Comment by JonasBley** [comment]
How do I force?

**Comment by inyono** [comment]
`git push --force <whatever>`

**Comment by JonasBley** [comment]
Ok this should work now

**Pull request merged**
